USE [master]
GO

/****** Object:  Database [OPENCUDMDB]    Script Date: 8/22/2022 5:22:22 PM ******/
DROP DATABASE [OPENCUDMDB]
GO

/****** Object:  Database [OPENCUDMDB]    Script Date: 8/22/2022 5:22:22 PM ******/
CREATE DATABASE [OPENCUDMDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OPENCUDMDB', FILENAME = N'C:\Databases\OPENCUDMDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OPENCUDMDB_log', FILENAME = N'C:\Databases\OPENCUDMDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OPENCUDMDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OPENCUDMDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OPENCUDMDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OPENCUDMDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OPENCUDMDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OPENCUDMDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET RECOVERY FULL 
GO

ALTER DATABASE [OPENCUDMDB] SET  MULTI_USER 
GO

ALTER DATABASE [OPENCUDMDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OPENCUDMDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OPENCUDMDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OPENCUDMDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OPENCUDMDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OPENCUDMDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OPENCUDMDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OPENCUDMDB] SET  READ_WRITE 
GO


